# confluent/kafka
# confluent/zookeeper

version: "3.3"

networks:
  kafka:
    driver: bridge

services:
  zk1:
    build:
      context: ./images/zookeeper
    restart: always
    ports:
      - "9911:2181"
    networks:
      - kafka
    volumes:
      - zk1_data:/opt/zookeeper/data
      - zk1_log:/opt/zookeeper/datalog
    environment:
      zk_myid: 0
      zk_servers: zk1,zk2,zk3
  zk2:
    build:
      context: ./images/zookeeper
    restart: always
    ports:
      - "9912:2181"
    networks:
      - kafka
    volumes:
      - zk2_data:/opt/zookeeper/data
      - zk2_log:/opt/zookeeper/datalog
    environment:
      zk_myid: 1
      zk_servers: zk1,zk2,zk3
  zk3:
    build:
      context: ./images/zookeeper
    restart: always
    ports:
      - "9913:2181"
    networks:
      - kafka
    volumes:
      - zk3_data:/opt/zookeeper/data
      - zk3_log:/opt/zookeeper/datalog
    environment:
      zk_myid: 2
      zk_servers: zk1,zk2,zk3
  

  kf1:
    build:
      context: ./images/kafka
    restart: always
    ports:
      - "9921:9092"
    networks:
      - kafka
    volumes:
      - kf1_log:/tmp/kafka-logs
    environment:
      cfg_zookeeper_connect: zk1:2181,zk2:2181,zk3:2181
      cfg_broker_id: 1
      cfg_advertised_listeners: PLAINTEXT://$DOCKER_IP:9921
  
  kf2:
    build:
      context: ./images/kafka
    restart: always
    ports:
      - "9922:9092"
    networks:
      - kafka
    volumes:
      - kf2_log:/tmp/kafka-logs
    environment:
      cfg_zookeeper_connect: zk1:2181,zk2:2181,zk3:2181
      cfg_broker_id: 2
      cfg_advertised_listeners: PLAINTEXT://$DOCKER_IP:9922
  
  kf3:
    build:
      context: ./images/kafka
    restart: always
    ports:
      - "9923:9092"
    networks:
      - kafka
    volumes:
      - kf3_log:/tmp/kafka-logs
    environment:
      cfg_zookeeper_connect: zk1:2181,zk2:2181,zk3:2181
      cfg_broker_id: 3
      cfg_advertised_listeners: PLAINTEXT://$DOCKER_IP:9923

  schemareg:
    hostname: schema_registry
    image: confluentinc/cp-schema-registry:3.3.0
    restart: always
    ports:
      - "8081:8081"
    networks:
      - kafka
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zk1:2181,zk2:2181,zk3:2181

volumes:
  zk1_data:
  zk1_log:
  zk2_data:
  zk2_log:
  zk3_data:
  zk3_log:
  kf1_log:
  kf2_log:
  kf3_log: